language: java
sudo: false
script:
  - cd webapp
  - mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=aws"
notifications:
  email:
    recipients:
      - gohel.n@husky.neu.edu
      - indap.n@husky.neu.edu
      - chugh.k@husky.neu.edu
  on_success: always
  on_failure: always
